// Path: lib/data/services/database_service.dart

import 'package:cloud_firestore/cloud_firestore.dart';
import '../../models/menu_item_model.dart';
import '../../models/order_model.dart';
import '../../models/table_model.dart';

class DatabaseService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  // 1. GET MENU ITEMS (REAL-TIME STREAM)
  Stream<List<MenuItemModel>> getMenuItemsStream() {
    return _db.collection('menu_items').snapshots().map((snapshot) {
      return snapshot.docs.map((doc) {
        return MenuItemModel.fromFirestore(doc.data(), doc.id);
      }).toList();
    });
  }

  // 2. UPDATE OUT-OF-STOCK STATUS (FOR MANAGER)
  Future<void> updateSoldOutStatus(String itemId, bool isSoldOut) async {
    try {
      await _db.collection('menu_items').doc(itemId).update({
        'is_sold_out': isSoldOut,
      });
    } catch (e) {
      print("Error updating status: \$e");
      rethrow;
    }
  }

  // 3. CREATE NEW ORDER (FOR CUSTOMER)
  Future<String> placeOrder(OrderModel order) async {
    try {
      final docRef = _db.collection('orders').doc();
      // Update the empty orderId with the real one generated by Firebase
      order.orderId = docRef.id;
      final orderData = order.toFirestore();
      await docRef.set(orderData);

      return docRef.id; // Return the generated ID
    } catch (e) {
      print("Error placing order: \$e");
      rethrow;
    }
  }

  // 4. GET PENDING ORDERS (REAL-TIME STREAM FOR KDS)
  Stream<List<OrderModel>> getPendingOrdersStream() {
    return _db
        .collection('orders')
        .where('status', isEqualTo: 'pending')
        .orderBy('created_at', descending: false)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs.map((doc) {
            return OrderModel.fromFirestore(doc.data(), doc.id);
          }).toList();
        });
  }

  // 5. UPDATE ORDER STATUS (WHEN KITCHEN SWIPES TO READY)
  Future<void> updateOrderStatus(String orderId, String newStatus) async {
    try {
      await _db.collection('orders').doc(orderId).update({'status': newStatus});
    } catch (e) {
      print("Error updating order status: \$e");
      rethrow;
    }
  }

  // 6. ADD NEW MENU ITEM (FOR MANAGER)
  Future<void> addMenuItem(MenuItemModel item) async {
    try {
      final docRef = _db.collection('menu_items').doc();
      final data = item.toFirestore();
      await docRef.set(data);
    } catch (e) {
      print("Error adding menu item: \$e");
      rethrow;
    }
  }

  // 6B. CLEAR ALL MENU ITEMS (FOR SEEDING)
  Future<void> clearMenuItems() async {
    final snapshot = await _db.collection('menu_items').get();
    for (var doc in snapshot.docs) {
      await doc.reference.delete();
    }
  }

  // 7. GET ACTIVE ORDERS FOR WAITER (PENDING & READY)
  Stream<List<OrderModel>> getActiveOrdersStream() {
    return _db
        .collection('orders')
        .where('status', whereIn: ['pending', 'ready'])
        .snapshots()
        .map((snapshot) {
          final orders = snapshot.docs.map((doc) {
            return OrderModel.fromFirestore(doc.data(), doc.id);
          }).toList();

          // Sort client-side to prevent Firestore composite index requirements
          orders.sort((a, b) => a.createdAt.compareTo(b.createdAt));
          return orders;
        });
  }

  // 8. ADD NEW TABLE (FOR MANAGER)
  Future<void> addTable(int tableNumber) async {
    try {
      final docRef = _db.collection('tables').doc();
      final qrData = 'makanje://table/$tableNumber'; // Deep link or QR payload
      final newTable = TableModel(
        id: docRef.id,
        tableNumber: tableNumber,
        qrData: qrData,
        createdAt: DateTime.now(),
      );
      await docRef.set(newTable.toFirestore());
    } catch (e) {
      print("Error adding table: $e");
      rethrow;
    }
  }

  // 9. GET TABLES STREAM (FOR MANAGER)
  Stream<List<TableModel>> getTablesStream() {
    return _db
        .collection('tables')
        .orderBy('table_number', descending: false)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs.map((doc) {
            return TableModel.fromFirestore(doc.data(), doc.id);
          }).toList();
        });
  }

  // 10. GET ACTIVE ORDERS FOR A SPECIFIC TABLE (CUSTOMER)
  Future<List<OrderModel>> getActiveOrdersForTable(int tableNumber) async {
    final querySnapshot = await _db
        .collection('orders')
        .where('table_number', isEqualTo: tableNumber)
        .where('status', whereIn: ['pending', 'cooking', 'ready', 'completed'])
        .get();

    final orders = querySnapshot.docs
        .map((doc) => OrderModel.fromFirestore(doc.data(), doc.id))
        .toList();

    orders.sort((a, b) => a.createdAt.compareTo(b.createdAt));
    return orders;
  }

  // 11. GET ALL PAID ORDERS FOR ANALYTICS (MANAGER)
  Stream<List<OrderModel>> getPaidOrdersStream() {
    return _db
        .collection('orders')
        .where('status', isEqualTo: 'paid')
        .snapshots()
        .map((snapshot) {
          final orders = snapshot.docs.map((doc) {
            return OrderModel.fromFirestore(doc.data(), doc.id);
          }).toList();

          orders.sort((a, b) => a.createdAt.compareTo(b.createdAt));
          return orders;
        });
  }

  // 12. UPDATE EXISTING MENU ITEM (FOR MANAGER)
  Future<void> updateMenuItem(MenuItemModel item) async {
    try {
      await _db
          .collection('menu_items')
          .doc(item.itemId)
          .update(item.toFirestore());
    } catch (e) {
      print("Error updating menu item: $e");
      rethrow;
    }
  }

  // 13. DELETE MENU ITEM (FOR MANAGER)
  Future<void> deleteMenuItem(String itemId) async {
    try {
      await _db.collection('menu_items').doc(itemId).delete();
    } catch (e) {
      print("Error deleting menu item: $e");
      rethrow;
    }
  }

  // lib/data/services/database_service.dart

  // Update payment status for specific items within an order
  Future<void> updateItemsAsPaid(String orderId, List<int> itemIndices) async {
    try {
      DocumentReference orderRef = _db.collection('orders').doc(orderId);

      // 1. Get the latest data from Firestore
      DocumentSnapshot doc = await orderRef.get();
      if (!doc.exists) return;

      Map<String, dynamic> data = doc.data() as Map<String, dynamic>;
      List<dynamic> items = List.from(data['items']);

      // 2. Mark selected indices as paid
      for (int index in itemIndices) {
        if (index < items.length) {
          items[index]['is_paid'] = true;
        }
      }

      // 3. Update the whole list back to Firestore
      await orderRef.update({'items': items});

      // 4. Distinction Point: Check if ALL items in this order are paid
      bool allPaid = items.every((item) => item['is_paid'] == true);
      if (allPaid) {
        await orderRef.update({'status': 'paid'}); // Auto-close the order
      }
    } catch (e) {
      print("Error updating items payment: $e");
      rethrow;
    }
  }

  Future<void> markOrderItemAsPaid(String orderId, int itemIndex) async {
    try {
      DocumentReference orderRef = _db.collection('orders').doc(orderId);
      DocumentSnapshot doc = await orderRef.get();

      if (!doc.exists) return;

      // 1. Retrieve current order data
      Map<String, dynamic> data = doc.data() as Map<String, dynamic>;
      List<dynamic> items = List.from(data['items']);

      // 2. Mark the specified item as paid.
      if (itemIndex < items.length) {
        items[itemIndex]['is_paid'] = true;
      }

      // 3. Check if all the dishes have been paid for.
      bool allPaid = items.every((item) => item['is_paid'] == true);

      // 4. Update Firebase
      Map<String, dynamic> updates = {'items': items};
      if (allPaid) {
        updates['status'] =
            'paid'; // The overall status will only be changed after all payments are completed.
      }

      await orderRef.update(updates);
    } catch (e) {
      print("Error marking item as paid: $e");
      rethrow;
    }
  }
}
