// Path: lib/data/services/database_service.dart

import 'package:cloud_firestore/cloud_firestore.dart';
import '../../models/menu_item_model.dart';
import '../../models/order_model.dart';

class DatabaseService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  // 1. GET MENU ITEMS (REAL-TIME STREAM)
  Stream<List<MenuItemModel>> getMenuItemsStream() {
    return _db.collection('menu_items').snapshots().map((snapshot) {
      return snapshot.docs.map((doc) {
        return MenuItemModel.fromFirestore(doc.data(), doc.id);
      }).toList();
    });
  }

  // 2. UPDATE OUT-OF-STOCK STATUS (FOR MANAGER)
  Future<void> updateSoldOutStatus(String itemId, bool isSoldOut) async {
    try {
      await _db.collection('menu_items').doc(itemId).update({
        'is_sold_out': isSoldOut,
      });
    } catch (e) {
      print("Error updating status: $e");
      rethrow;
    }
  }

  // 3. CREATE NEW ORDER (FOR CUSTOMER)
  // 3. CREATE NEW ORDER (FOR CUSTOMER)
  Future<String> placeOrder(OrderModel order) async {
    try {
      final docRef = _db.collection('orders').doc();
      // Update the empty orderId with the real one generated by Firebase
      order.orderId = docRef.id;
      final orderData = order.toFirestore();
      await docRef.set(orderData);

      return docRef.id; // Return the generated ID
    } catch (e) {
      print("Error placing order: $e");
      rethrow;
    }
  }

  // 4. GET PENDING ORDERS (REAL-TIME STREAM FOR KDS)
  Stream<List<OrderModel>> getPendingOrdersStream() {
    return _db
        .collection('orders')
        .where('status', isEqualTo: 'pending')
        .orderBy('created_at', descending: false)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs.map((doc) {
            return OrderModel.fromFirestore(doc.data(), doc.id);
          }).toList();
        });
  }

  // 5. UPDATE ORDER STATUS (WHEN KITCHEN SWIPES TO READY)
  Future<void> updateOrderStatus(String orderId, String newStatus) async {
    try {
      await _db.collection('orders').doc(orderId).update({'status': newStatus});
    } catch (e) {
      print("Error updating order status: $e");
      rethrow;
    }
  }
}
